dist: xenial
sudo: required

branches:
  only:
    - master

cache:
    directories:
      - $HOME/.cache
 
env:
    global:
      # Environment variables for packaging
      - PRODUCT=flameshot
      - VERSION=0.6.0
      - RELEASE=1
      - ARCH=x86_64
      - SNAP_DOCKER_REPO=snapcore/snapcraft
      - FLATPAK_DOCKER_REPO=vitzy/flameshot:fedora-28
      # - FLATPAK_GNOME_DOCKER_REPO=vitzy/flatpak:flatpak-gnome
      # - FLATPAK_KDE_DOCKER_REPO=vitzy/flatpak:flatpak-kde
      # - FLATPAK_FREEDESKTOP_DOCKER_REPO=vitzy/flatpak:flatpak-freedesktop

matrix:
    include:
        - os: linux
          env: OS=ubuntu DIST=xenial EXTEN=snap
          services: docker
          language: cpp
        - os: linux
          env: OS=ubuntu DIST=xenial EXTEN=appimage
          language: cpp
        - os: linux
          env: OS=fedora DIST=29 EXTEN=flatpak RUN_TIME=gnome
          language: cpp
        # - os: linux
        #   env: OS=fedora DIST=29 EXTEN=flatpak RUN_TIME=kde
        #   language: cpp
        # - os: linux
        #   env: OS=fedora DIST=29 EXTEN=flatpak RUN_TIME=freedesktop
        #   language: cpp
       
before_install:
  - export ROOT_PATH="$(pwd)"
  - git clone https://github.com/lupoDharkael/flameshot
  - export SRC_PATH="${ROOT_PATH}/flameshot"
  - chmod +x ${ROOT_PATH}/scripts/*.sh
  - if [[ "${EXTEN}" == "snap" ]]; then source ${ROOT_PATH}/scripts/snap_before_install.sh; fi
  - if [[ "${EXTEN}" == "appimage" ]]; then source ${ROOT_PATH}/scripts/appimage_before_install.sh; fi
  - if [[ "${EXTEN}" == "flatpak" ]]; then source ${ROOT_PATH}/scripts/flatpak_before_install.sh; fi

install:
  - if [[ "${EXTEN}" == "snap" ]]; then source ${ROOT_PATH}/scripts/snap_install.sh; fi
  - if [[ "${EXTEN}" == "appimage" ]]; then source ${ROOT_PATH}/scripts/appimage_install.sh; fi
  - if [[ "${EXTEN}" == "flatpak" ]]; then source ${ROOT_PATH}/scripts/flatpak_install.sh; fi

script:
  - if [[ "${EXTEN}" == "snap" ]]; then source ${ROOT_PATH}/scripts/snap_script.sh; fi
  - if [[ "${EXTEN}" == "appimage" ]]; then source ${ROOT_PATH}/scripts/appimage_script.sh; fi
  - if [[ "${EXTEN}" == "flatpak" ]]; then source ${ROOT_PATH}/scripts/flatpak_script.sh; fi
  - pwd && ls

after_success:
  - if [[ "${EXTEN}" == "snap" ]]; then source ${ROOT_PATH}/scripts/snap_after_success.sh; fi
  - if [[ "${EXTEN}" == "appimage" ]]; then source ${ROOT_PATH}/scripts/appimage_after_success.sh; fi
  - echo "Download URL is $TEMP_DOWNLOAD_URL ."
